# Number of people in a full car
FULL_CAR_SIZE = 4

# The number of age groups will be consolidated into at most this many groups
NUM_AGE_GROUPS = 3

# Used on 1st day to penalize if there is only 1 academy studen in a car group
ACADEMY_WEIGHT = 1
# Used on 1st day to penalize if an academy BIPOC student is the only BIPOC in car group
BIPOC_WEIGHT = 1
# How much to weight age diversity
AGE_WEIGHT = 1
# How much to weight experience diversity
EXP_WEIGHT = 1
# How much to weight not having previously been in same car
PREV_WEIGHT = 3