SHEET_INDICATOR = '!'
FULL_ROSTER_WORKSHEET = SHEET_INDICATOR + 'Detailed Roster from App'
ROSTER_WORKSHEET = SHEET_INDICATOR + 'Roster for Car Grouping'
DRIVER_WORKSHEET = SHEET_INDICATOR + "Drivers"
CAR_GROUP_WORKSHEET = SHEET_INDICATOR + 'Car Group {}'
DETAILED_CAR_GROUP_WORKSHEET = SHEET_INDICATOR + 'Detailed Car Group {}'